### PR TITLE
Update imports to work with novaclient 3.4.0

### PR DESCRIPTION
**Pull request by jasondunsmore**

### CODE REVIEW

**Comment by coderanger** [comment]
If you wanted to keep backwards compat you could make that:

```python
try:
    from novaclient.openstack.common import cliutils as utils
except ImportError
    from novaclient import utils
```

**Comment by jtwebman** [comment]
novaclient 4.0.0 has the same issue with this. Took me hours to figure it out. @rackerlabs Can you please merge this and release it!!

**Comment by rgbkrk** [comment]
Merging, charging ahead. I use `rack` exclusively now and its the tooling my team supports officially. @jasondunsmore would you like to manage releases for both of these?

**Comment by rgbkrk** [comment]
Looks like I don't have access to this one on PyPI so it's up to @asadoughi to get it done.

If there's not resolution soon, I'd push for taking out the ip extensions from the rackspace novaclient. This is not the first time we've had trouble around with these extensions in particular.

**Comment by jtwebman** [comment]
@rgbkrk Does rack do everything Nova does?

**Comment by rgbkrk** [comment]
`rack` explicitly doesn't help you do operations work, it's designed around being a user tool first and foremost.

**Comment by jkoelker** [comment]
@rgbkrk I ping'd @roaet on irc to give you PyPi perms.

**Comment by roaet** [comment]
@rgbkrk done

**Pull request merged**
